version: '3.8'
services:
  db:
    image: postgres:15
    container_name: uex_contacts_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uex_contacts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: uex_contacts_app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/uex_contacts
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"

volumes:
  postgres_data: